### ISSUE TITLE
Do Content-Type header compressibility checking

### ISSUE THREAD

**Issue by Fishrock123** [Fishrock123/tide-compress#6]
To solve this kinda thing https://github.com/ttiurani/tide-compress/commit/1127c91e9e2b7ea52cb505ff432222ce05baeaf4

Basically, we'd need to re-implement https://github.com/jshttp/compressible and (more importantly) the database at https://github.com/jshttp/mime-db/blob/master/db.json

So, tasks:

- Make this have an option for the very basic regex search
- Somehow import mime-db at *compile time*

**Comment by Fishrock123** [comment]
Regex checking in https://github.com/Fishrock123/tide-compress/commit/65bd357a79c6b767aa9c6bf715ac82c0cbc98595

MIME database checking in https://github.com/Fishrock123/tide-compress/commit/61f8b84e4d0f7c879ecbe919bc3c76deea9e9c65

**Comment by Fishrock123** [comment]
Released in 0.10 https://github.com/Fishrock123/tide-compress/releases/tag/0.10.0

**Comment by Fishrock123** [comment]
@ttiurani can you see if this accurately solves your problem so you no longer need your patch?

**Comment by ttiurani** [comment]
Hi! This is great! I didn't ping you about my fork, because I didn't actually need my fork after all. But that's only because I needed to do my own implementation of `serve_dir` (`/example` needs to look for `example.html` and I needed custom headers and a cache). With my own implementation I was able to set the `Cache-Control: no-transform` header tide-compress already supported.

Furthermore, I haven't had time to look why exactly the `.wasm` file compression fails. I believe [it should work](https://github.com/jshttp/mime-db/blob/master/db.json#L5663), but there's some weird browser-side issue I'm hitting.

Having said that, I'll be sure to use your new `db-check` feature, to have all those `compressible: false` MIME types just work(tm)!
